config/routes.rb
Rails.application.routes.draw do
  resources :pages

  root "pages#landing"
  get '/work', to: 'pages#work'
  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def work
    @video_url = "https://www.youtube.com/embed/Oug6tdHidaM"
    @secondvideo_url = "https://www.youtube.com/embed/N-arOSS5wUc"
    @thirdvideo_url = "https://www.youtube.com/embed/gmzjHs_Ein8"
    @forthvideo_url = "https://www.youtube.com/embed/StO8JA2odAk"
    @fivevideo_url = "https://www.youtube.com/embed/ffzCQFbP0g0"
    @sixvideo_url = "https://www.youtube.com/embed/24HQ7S2qyd8"
    @sevenvideo_url = "https://www.youtube.com/embed/hjYxM9a-KKk"
    @eightvideo_url = "https://www.youtube.com/embed/w4Q15t9aANU"
  end

  # GET /pages/1 or /pages/1.json
  def landing
  end

  def about
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.fetch(:page, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matt Casillas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Alegreya|Questrial" rel="stylesheet">
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
</div>

app/views/pages/about.html.erb
<% @show_navbar = true %>
<h1 class="text-center pt-3">about me</h1>
<div class="text-center">
<%= image_tag 'headshot.jpeg', class: 'w-75 p-3'%>
</div>
<h4 class="text-center pt-3">Matt Casillas is a Mexican-American actor, writer, and director born and raised in Chicago, IL. He played multiple roles as part of CPS Shakespeare at the Chicago Shakespeare Theater in Navy Pier for productions of A Midsumers Night Dream and Othello. He is a graduate of the Conservatory program at The Second City Training Center. He is a part of the sketch comedy troupe, OffPinkFloyd. He is also great with pets and parents. </h4>
<br>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<div class="container text-center pt-3">
  <button type="button" class="btn btn-dark p-2" style="width: 100px;" onclick="window.location.href='/about';">About me</button>
</div>
<br>
<div class="row row-cols-1 row-cols-md-2 g-4">
  <div class="col">
    <div class="card">
      <%= image_tag "profpic.jpeg", class: "card-img-top", alt: "Photo 1" %>
      <div class="card-body">
        <h5 class="card-title">Photo #1</h5>
        <p class="card-text">This is a description</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <%= image_tag "profpic2.jpeg", class: "card-img-top", alt: "Photo 2" %>
      <div class="card-body">
        <h5 class="card-title">Photo 2</h5>
        <p class="card-text">This is a description</p>
      </div>
    </div>
  </div>
</div>
<div class="video">
  <iframe width="560" height="315" src="<%= @video_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<br>
<p class="text-center">
  This is a quick description of what this video is about.
</p>
<br>
<div class="video">
  <iframe width="560" height="315" src="<%= @secondvideo_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class='text-center'> This is a description.
</p>
<br>
<br>
<div class="video">
  <iframe width="560" height="315" src="<%= @thirdvideo_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class='text-center'> This is a description.
</p>
<br>
<br>
<div class="video">
  <iframe width="560" height="315" src="<%= @forthvideo_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class='text-center'> This is a description.
</p>
<br>
<div class="container text-center pt-3">
  <button type="button" class="btn btn-dark p-2" style="width: 100px;" onclick="window.location.href='/about';">About me
  </button>
</div>

app/views/pages/landing.html.erb
<% @show_navbar = false %>
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="text-center">
    <%= image_tag 'mc.png' %>
    <%= button_to "work.", "/work", method: :get, class: "btn btn-outline-secondary" %>
    <%= button_to "about me.", "/about", method: :get, class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>

app/views/pages/work.html.erb
<% @show_navbar = true %>
<div class="container text-center pt-3">
  <button type="button" class="btn btn-dark p-2" style="width: 100px;" onclick="window.location.href='/about';">about me.</button>
</div>
<div class="video">
  <iframe width="560" height="315" src="<%= @video_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<br>
<p class="text-center pt-3">
  Sketch created by the comedy troupe, OffPinkFloyd
</p>
<div class="container text-center pt-4">
  <div class="container">
    <div class="row justify-content-center"> <!-- Center the row -->
      <div class="col-md-6"> <!-- Specify the column width -->
        <div class="card">
          <%= image_tag "poster1.jpeg", class: "card-img-top", alt: "Photo 1" %>
          <div class="card-body">
            <h4 class="card-title fw-bold">It's My Party I Can Die If I Want To.</h4>
            <p class="card-text">Second City Conservatory Grad Revue show poster.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="video">
  <iframe width="560" height="315" src="<%= @secondvideo_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class='text-center'> Sketch by comedy troupe, OffPinkFloyd.
</p>
<br>
<br>
<div class="video">
  <iframe width="560" height="315" src="<%= @thirdvideo_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class='text-center'> Blackout sketch titled Ty Lue from the Second City Conservatory Grad Revue show: "Its My Party I Can Die If I Want To" by the comedy troupe, Hell Yea Brother.
</p>
<br>
<br>
<div class="video">
  <iframe width="560" height="315" src="<%= @forthvideo_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class='text-center'> Sketch from the Second City Conservatory Grad Revue Show: "It's My Party I Can Die If I Want To" by the comedy troupe Hell Yea Brother.
</p>
<br>
<div class="container text-center pt-3">
  <div class="container">
    <div class="row justify-content-center"> <!-- Center the row -->
      <div class="col-md-6"> <!-- Specify the column width -->
        <div class="card">
          <%= image_tag "poster2.jpeg", class: "card-img-top", alt: "Poster 2" %>
          <div class="card-body">
            <h5 class="card-title">Laughter, Rinse, Repeat.</h5>
            <p class="card-text">Second City Directors Showcase poster.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="video">
  <iframe width="560" height="315" src="<%= @fivevideo_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class='text-center'> Sketch from the Second City Conservatory Grad Revue Show: "It's My Party I Can Die If I Want To" by the comedy troupe Hell Yea Brother.
</p>
<div class="video">
  <iframe width="560" height="315" src="<%= @sixvideo_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class='text-center'> Sketch by the comedy troupe, OffPinkFloyd.
</p>
<div class="video">
  <iframe width="560" height="315" src="<%= @sevenvideo_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class='text-center'> Sketch by the comedy troupe OffPinkFloyd.
</p>
<div class="video">
  <iframe width="560" height="315" src="<%= @eightvideo_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class='text-center'> Short film written, directed, and starring Brenda Reyes and Matt Casillas.
</p>
<!--keep this at the end-->
<button type="button" class="btn btn-dark p-2 d-block mx-auto" style="width: 100px;" onclick="window.location.href='/about';">about me.</button>

app/views/shared/_navbar.html.erb
<% if @show_navbar %>
  <nav class="navbar bg-body-tertiary">
    <div class="container justify-content-center">
      <a class="navbar-brand" href="/">
        <%=image_tag 'mc.png' , class: 'center-image'%>
      </a>
    </div>
  </nav>
<% end %>